### ISSUE TITLE
Candle Manager does not seem to work anymore

### ISSUE THREAD

**Issue by jcmarze** [createcandle/Candle-manager-addon#8]
Hi,

unclear why, but after 2 attempts from scratch, the issue can be repeated.

After adding the Candle Manager v1.0.4, and clicking on the "+" in the empty "Things" menu/screen, I get a message of "No new things found ..."

A new menu entry "Candle Manager" has been created in the menu (just before "log out"), but there is no option to add anything there.

Note: I loaded a version in November of the Candle Manager, and while I had some issues, it allowed me to create the receiver and a plant sensor. I am unable to get to that point now however (I am using the same Raspberry PI).

Thanks,

JC

**Comment by wanjatschuor** [comment]
Same here.

**Comment by createcandle** [comment]
Yes, the 'thing' was removed, since you should now be able to just open the Candle Manager from the menu. But this only worked if you had skipped the option to create a `something.mozilla.org` domain. After all, Candle was all about not connecting your home to the internet.

But by popular demand it now also works if you do connect your system to the web.
